"""Create token_created_at field

Revision ID: 14a3236205a5
Revises: 9f9b041ee4ba
Create Date: 2019-09-02 12:02:20.819749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a3236205a5'
down_revision = '9f9b041ee4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_created_at')
    # ### end Alembic commands ###
