"""Contact ON DELETE CASCADE

Revision ID: 3d6588bea33c
Revises: 14a3236205a5
Create Date: 2019-09-03 21:06:52.067786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6588bea33c'
down_revision = '14a3236205a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_contact_id_fkey', 'contacts', type_='foreignkey')
    op.drop_constraint('contacts_owner_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contacts', 'users', ['contact_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_owner_id_fkey', 'contacts', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('contacts_contact_id_fkey', 'contacts', 'users', ['contact_id'], ['id'])
    # ### end Alembic commands ###
