"""Add UNIQUE TOGETHER for Contacts Foreign keys

Revision ID: 9f9b041ee4ba
Revises: b42042f49a92
Create Date: 2019-08-30 17:59:24.415558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9b041ee4ba'
down_revision = 'b42042f49a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contacts_owner_contact', 'contacts', ['owner_id', 'contact_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_owner_contact', 'contacts', type_='unique')
    # ### end Alembic commands ###
