"""Added last_message_text to group_room models

Revision ID: ab5ded22806c
Revises: 927d3fe34e48
Create Date: 2019-09-22 19:17:09.064726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5ded22806c'
down_revision = '927d3fe34e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_rooms', sa.Column('last_message_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_rooms', 'last_message_text')
    # ### end Alembic commands ###
